package GUI.Panel;

import GUI.Main;
import java.awt.Dimension;
import javax.swing.JPanel;
import style.style;

/**
 *
 * @author phucp
 */
public class DichVu extends JPanel {

    style style = new style();
    Main main;

    public DichVu(Main main) {
        this.main = main;
        initComponents();
        initComponent();
    }

    public void initComponent() {
        this.setSize(new Dimension(1030, 670));
        this.setBackground(style.mainBackgroundColorOrange());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
