package GUI.Panel;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import GUI.Component.TableModel;
import GUI.Main;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import style.style;

/**
 *
 * @author phucp
 */
public class KhachHang extends JPanel implements ActionListener, ItemListener {

    style style = new style();
    Main m;
    public KhachHangBUS khachhangBUS = new KhachHangBUS();
    public ArrayList<KhachHangDTO> listkh = khachhangBUS.getAll();

    public KhachHang(Main m) {
        this.m = m;
        initComponents();
        initComponent();

    }

    public void initComponent() {
        this.setSize(new Dimension(1030, 670));
        this.setBackground(style.mainBackgroundColor());
        this.setLayout(new BorderLayout(0, 0));
        this.setOpaque(true);
        this.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        String[] header = new String[]{"Mã khách hàng", "Tên khách hàng", "Email", "Số điện thoại", "Vai trò", "Ngày tham gia"};
        String[] methodNames = {"getID", "getTen_Nguoi_Dung", "getEmail", "getSo_Dien_Thoai", "getVai_Tro", "getNgay_Tao"};

        TableModel<KhachHangDTO> tableModel = new TableModel<>(listkh, header, methodNames);
        JTable table = new JTable(tableModel);

        style.customizeTable(table);

        JScrollPane scrollPane = new JScrollPane(table);
        this.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setBorder(null);
        scrollPane.getViewport().setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
