package GUI.Panel;

import GUI.Component.TitleHome;
import java.awt.*;
import javax.swing.*;
import style.StyleColor;
import style.style;

/**
 *
 * @author phucp
 */
public class TrangChu extends JPanel {

    style style = new style();
    StyleColor colorStyle = new StyleColor();

    JPanel top, center, bar1, bar2;

    public TrangChu() {
        initComponents();
        initComponent();
    }

    public void initComponent() {
//        this.setSize(new Dimension(1030, 670));
        this.setBounds(0, 200, 300, 1030);
        this.setBackground(style.mainBackgroundColor());
        this.setLayout(new BorderLayout(0, 0));
        this.setOpaque(true);

        top = new JPanel(new GridLayout(8, 1, 5, 5));
        top.setBackground(colorStyle.mainBackgroundColor1());
        top.setPreferredSize(new Dimension(1100, 450));
//        top.setLayout(new BorderLayout());
        top.setBorder(BorderFactory.createEmptyBorder(20, 10, 10, 10));

        TitleHome title = new TitleHome("TRƯỜNG ĐẠI HỌC QUỐC GIA - TRƯỜNG ĐAI HỌC CÔNG NGHỆ THÔNG TIN", 13);
        top.add(title);

        TitleHome titleBB = new TitleHome("BÁO CÁO ĐỒ ÁN", 30);
        top.add(titleBB);
        TitleHome titleB = new TitleHome("IE303.E22.LT.CNTT - CÔNG NGHỆ JAVA ", 28);
        top.add(titleB);
        TitleHome titleA = new TitleHome("HỆ THỐNG SÂN CẦU LÔNG", 18);
        top.add(titleA);
        TitleHome titleC = new TitleHome("NHÓM 10", "LỚP LT.K2024.1", 20, 20);
        top.add(titleC);
        TitleHome titleD1 = new TitleHome("Ngô Thị Châu Phụng", "MSSV: 24410087", 16, 16);
        top.add(titleD1);
        TitleHome titleD2 = new TitleHome("Đỗ Hùng Mạnh", "MSSV: 24410067", 16, 16);
        top.add(titleD2);
        TitleHome titleD3 = new TitleHome("Phạm Hồng Phúc", "MSSV: 24410086", 16, 16);
        top.add(titleD3);

        this.add(top, BorderLayout.NORTH);

        center = new JPanel();
        center.setBackground(colorStyle.mainBackgroundColor());
        center.setPreferredSize(new Dimension(1100, 400));
        center.setLayout(new FlowLayout(1, 50, 50));
        this.add(center, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
